version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: food_delivery_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: food_delivery
    ports:
      - "3306:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    container_name: food_delivery_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/food_delivery
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: food_delivery_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend 